# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-19 10:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('news', '0002_newsindexpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspage',
            name='main_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
