# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-19 16:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20180120_0048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newscategory',
            options={'verbose_name_plural': 'категории'},
        ),
    ]
