# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-09 18:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_blogpage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogIndexPage',
            new_name='PostIndexPage',
        ),
        migrations.RenameModel(
            old_name='BlogPage',
            new_name='PostPage',
        ),
    ]
