# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-11 18:05
from __future__ import unicode_literals

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20180111_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpage',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='post.PostCategory'),
        ),
    ]
