# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-12 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_gallerypage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerypage',
            name='date',
            field=models.DateField(verbose_name='data'),
        ),
    ]
