# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-20 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumsindexpage',
            name='intro',
            field=models.CharField(max_length=250),
        ),
    ]
